services:
  - name: b-api
    type: web
    buildCommand: npm run build
    startCommand: npm start
    env:
      - key: ENV
        value: DEVELOPMENT
routes:
  - path: '/api/*'
    service: b-api
  - path: '/*'
    service: b-api
